
Turn 1
================================================================
error: failed to decode bot message: "T" (at position 1)
Last input received was:
Traceback (most recent call last):
  File "MyBot.py", line 83, in <module>
    logging.info(me.get_dropoffs())
NameError: name 'me' is not defined

